#!/usr/bin/python

import pygst
pygst.require("0.10")
import gst
import pygtk
import gtk
import gtk.glade
import gobject
import os
import sys
import time


from conf import Conf

class Main(object):
    MSECS_PER_TICK = 200
    MSECS_PER_SAVE = 30000          # save position once every 30 seconds

    DEFAULT_BOOK_IMAGE_W = 100
    DEFAULT_BOOK_IMAGE_H = 100

    COL_NUM=0
    COL_FILENAME=1

    def _rel_path(self, p):
        return os.path.join(os.path.dirname(os.path.realpath(__file__)), p)

    def __init__(self, app_name, *args, **kwargs):
        from playlist_handler import PlaylistFormatManager

        super(Main, self).__init__(*args, **kwargs)
        self._app_name = app_name

        self._conf = Conf(app_name)

        self._current_pos = None
        self._current_duration = None
        self._current_file = None
        self._current_playlist = None

        self._playlist_format_manager = PlaylistFormatManager()

        self._init_gui()
        self._init_gst()
        
        self._conf.load()

        if len(sys.argv) == 2:
            playlist = sys.argv[1]
            self._load_playlist(playlist)
        else:
            self._restore_playlist()

        self._main_win.show()

    def _restore_playlist(self):
        pl = self._conf.get_playlist()
        if pl:
            self._load_playlist(pl)

    def _init_gui(self):
        filename = self._rel_path("gui.glade")

        self._builder = gtk.Builder()
        self._builder.add_from_file(filename)
        self._builder.connect_signals(self)

        self._main_win = self._builder.get_object('mainwin')
        self._main_win.set_title(self._app_name)
        
        self._TIME_FORMAT = gst.Format(gst.FORMAT_TIME)

        self._playliststore = self._builder.get_object('playliststore')
        self._playPauseButton = self._builder.get_object('playPauseButton')

        self._slider = self._builder.get_object('playerHScale')
        self._slider.set_draw_value(False)

        self._bookCoverImage = self._builder.get_object('bookCoverImage')

        self._bookTitleLabel = self._builder.get_object('bookTitleLabel')
        self._chapterLabel = self._builder.get_object('chapterLabel')
        self._miscLabel = self._builder.get_object('miscLabel')

        self._statusbar = self._builder.get_object('statusbar')
        self._statusbar_context_id = self._statusbar.get_context_id(u"status")

        self._bookTitleLabel.set_label(u"")
        self._chapterLabel.set_label(u"")
        self._miscLabel.set_label(u"")

        self._about = self._builder.get_object('aboutdialog')

        # setup the playlist file dialog
        self._file_chooser = self._builder.get_object('playlistchooserdialog')
        self._init_file_chooser_filters()
        
        self._init_treeview()

        gobject.timeout_add(self.__class__.MSECS_PER_TICK, self.on_tick)
        gobject.timeout_add(self.__class__.MSECS_PER_SAVE, self.on_periodic_save)

        img_path = self._rel_path('images/book.png')
        img = self._load_image(img_path, self.__class__.DEFAULT_BOOK_IMAGE_W,self.__class__.DEFAULT_BOOK_IMAGE_H)
        self._bookCoverImage.set_from_pixbuf(img)

    def _init_treeview(self):
        # add treeview columns
        self._treeview = self._builder.get_object('playlistview')
        cell0 = gtk.CellRendererText()
        cell1 = gtk.CellRendererText()
        col0 = gtk.TreeViewColumn("Num", cell0, text=self.__class__.COL_NUM)
        col1 = gtk.TreeViewColumn("Filename", cell1, text=self.__class__.COL_FILENAME)
        self._treeview.append_column(col0)
        self._treeview.append_column(col1)

    def _init_file_chooser_filters(self):
        all_formats_filter = gtk.FileFilter()
        all_formats_filter.set_name("Recognised playlists")

        other_format_filters = []

        for filter_name, filter_exts in self._playlist_format_manager.supported_filters():
            f = gtk.FileFilter()
            f.set_name(filter_name)
            for ext in filter_exts:
                pat = u"*" + ext
                all_formats_filter.add_pattern(pat)
                f.add_pattern(pat)
            other_format_filters.append(f)

        self._file_chooser.add_filter(all_formats_filter)
        for filt in other_format_filters:
            self._file_chooser.add_filter(filt)

        self._file_chooser_allfiles_filter = gtk.FileFilter()
        self._file_chooser_allfiles_filter.set_name("All files")
        self._file_chooser_allfiles_filter.add_pattern("*")
        self._file_chooser.add_filter(self._file_chooser_allfiles_filter)

    def _init_gst(self):
        self._player = gst.element_factory_make("playbin2", "player")
        fakesink = gst.element_factory_make("fakesink", "fakesink")
        self._player.set_property("video-sink", fakesink)

        bus = self._player.get_bus()
        bus.add_signal_watch()
        bus.connect("message", self.on_message)

    def _load_image(self, fname, w, h):
        pixbuf = gtk.gdk.pixbuf_new_from_file(fname)
        new_pb = pixbuf.scale_simple(w,h,gtk.gdk.INTERP_BILINEAR)
        return new_pb

    def _restore_position_for_playlist(self, playlist, default_file):
        fpath, pos = self._conf.get_pos(playlist, default_file)
        self._play_new_file(fpath)
        self._change_slider_and_seek_to(pos)

    def _change_slider_and_seek_to(self, new_pos):
        self._change_slider_pos(new_pos)
        self._seek_to(new_pos)

    def _disable_slider(self):
        try:
            self._slider.handler_block_by_func(self.on_playerHScale_value_changed)
        except TypeError:
            pass

    def _enable_slider(self):
        try:
            self._slider.handler_unblock_by_func(self.on_playerHScale_value_changed)
        except TypeError:
            pass

    def _change_slider_pos(self, new_pos):
        self._disable_slider()
        self._slider.set_range(0.0, self._current_duration)
        self._slider.set_value(new_pos)
        self._enable_slider()

    def _seek_to(self, new_pos):
        self._current_pos = new_pos
        if self.is_playing():
            self._player.seek_simple(self._TIME_FORMAT, gst.SEEK_FLAG_FLUSH, new_pos)
        else:
            self._player.seek_simple(self._TIME_FORMAT, gst.SEEK_FLAG_SKIP, new_pos)

    def _delta_seek(self, delta):
        new_pos = self._current_pos + delta
        self._seek_to(new_pos)

    def is_playing(self):
        states = self._player.get_state()
        return states[1] == gst.STATE_PLAYING

    def _set_file(self, fpath):
        self._player.set_property("uri", "file://" + fpath)
        self._current_file = fpath
        self._change_slider_and_seek_to(0.0)

    def _prettify_fpath(self, fpath):
        basename = os.path.basename(fpath)
        basename.replace('_', ' ')
        basename = basename.split('.')[0]
        return basename

    def _play_new_file(self, fpath):
        self._stop()
        self._current_duration = 0.1 # we don't know, but assume this is more than 0, since gtkscale doesn't like it if max == min
        self._set_file(fpath)
        self._chapterLabel.set_label(self._prettify_fpath(fpath))
        self._miscLabel.set_label(u"")
        self._play()

    def _play(self):
        self._player.set_state(gst.STATE_PLAYING)
        self._playPauseButton.set_label("Pause")

    def _pause(self):
        self._player.set_state(gst.STATE_PAUSED)
        self._playPauseButton.set_label("Play")

    def _stop(self):
        self._seek_to(0.0)
        self._player.set_state(gst.STATE_NULL)
        self._current_pos = 0
        self._playPauseButton.set_label("Play")

    def on_book_open_menuitem_activate(self, widget):
        self._file_chooser.show()

    def _install_playlist_files(self, files):
        playliststore = self._builder.get_object("playliststore")
        playliststore.clear()
        count = 1
        for f in files:
            playliststore.append([count, f])
            count += 1

    def _playlist_handler_for(self, fpath):
        basename, ext = os.path.splitext(fpath)
        for h in self._playlist_handlers:
            if ext in h.extensions():
                return h
        return None

    def _load_playlist(self, fpath):
        handler = self._playlist_format_manager.handler_for_filepath(fpath)
        if handler is not None:
            book = handler.load_book(fpath)
            if book is not None:
                self._current_playlist = fpath
                self._bookTitleLabel.set_label(book.title())
                filelist = book.get_files()
                if filelist is not None:
                    self._install_playlist_files(filelist)
                    self._restore_position_for_playlist(self._current_playlist, filelist[0])
                    return
        self._statusbar.push(self._statusbar_context_id, "Couldn't load %s" % fpath)

    def on_playlistchooserdialog_file_activated(self, filedialog):
        filedialog.hide()
        self._load_playlist(filedialog.get_filename())

    def on_playlistview_cursor_changed(self, widget):
        path, col = widget.get_cursor()
        it = self._playliststore.get_iter(path)
        filepath = self._playliststore.get_value(it, 1)
        self._play_new_file(filepath)

    def _clear_current_file(self):
        self._chapterLabel.set_label(u"")
        self._miscLabel.set_label(u"")
        self._slider.set_range(0.0, 0.1)
        self._slider.set_value(0.0)

    def _prev_file(self):
        self._clear_current_file()
        
        current_file = self._current_file
        last_file = None
        prev_file = None
        for item in self._playliststore:
            if item[1] == current_file:
                prev_file = last_file
            last_file = item[1]

        if prev_file:
            self._play_new_file(prev_file)
        else:
            self._stop()

    def _next_file(self):
        self._clear_current_file()
    
        current_file = self._current_file
        num_items = len(self._playliststore)

        current_idx = None
        for idx, item in enumerate(self._playliststore):
            if item[1] == current_file:
                current_idx = idx

        next_file = None
        if current_idx is not None:
            next_idx = current_idx+1
            if next_idx < num_items:
                next_item = self._playliststore[next_idx]
                next_file = next_item[1]

        if next_file:
            self._play_new_file(next_file)
        else:
            self._stop()

    def on_message(self, bus, message):
        t = message.type

        if t == gst.MESSAGE_EOS:
            self._next_file()
        elif t == gst.MESSAGE_ERROR:
            self._stop()
            err, debug = message.parse_error()
            print "Error: %s" % err, debug

    def on_tick(self):
        if self.is_playing():
            try:
                self._current_duration = float(self._player.query_duration(self._TIME_FORMAT)[0])
                self._current_pos = self._player.query_position(self._TIME_FORMAT)[0]
                self._change_slider_pos(self._current_pos)

            except gst.QueryError:
                pass

        return True

    def on_playerHScale_value_changed(self, widget):
        val = widget.get_value()
        self._seek_to(val)

    def on_playPauseButton_clicked(self, widget):
        if self.is_playing():
            self._pause()
        else:
            self._play()

    def on_previousButton_clicked(self, widget):
        self._prev_file()

    def on_backButton_clicked(self, widget):
        self._delta_seek(self._seconds_to_ns(-5))

    def on_forwardButton_clicked(self, widget):
        self._delta_seek(self._seconds_to_ns(5))

    def on_nextButton_clicked(self, widget):
        self._next_file()

    def save(self):
        self._conf.set_playlist(self._current_playlist)
        self._conf.set_pos(self._current_playlist, self._current_file, self._current_pos)
        self._conf.save()

    def _seconds_to_ns(self, secs):
        return secs * 1000000000

    def on_periodic_save(self):
        if self.is_playing():
            self.save()

    def _quit(self):
        if self._current_playlist and self._current_file:
            self.save()
        self._conf.save()
        gtk.main_quit()

    def on_mainwin_destroy(self, widget):
        self._quit()

    def on_app_quit_menuitem_activate(self, widget):
        self._quit()

    def on_about_menuitem_activate(self, widget):
        self._about.show()

    def on_aboutdialog_response(self, widget, ev):
        widget.hide()

if __name__ == "__main__":
    app = Main("PlayaPlaya")
    gtk.gdk.threads_init()

    try:
        try:
            gtk.main()
        finally:
            if app.is_playing():
                app.save()
    except (KeyboardInterrupt, SystemExit), ex:
        pass

